<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Flower;
use Illuminate\Support\Str;

class FlowerCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Crear categorías si no existen
        $categories = [
            ['name' => 'Rosas', 'slug' => 'rosas', 'description' => 'Hermosas rosas en diversos colores'],
            ['name' => 'Tulipanes', 'slug' => 'tulipanes', 'description' => 'Tulipanes frescos y coloridos'],
            ['name' => 'Girasoles', 'slug' => 'girasoles', 'description' => 'Girasoles radiantes y alegres'],
            ['name' => 'Orquídeas', 'slug' => 'orquideas', 'description' => 'Orquídeas exóticas y elegantes'],
            ['name' => 'Peonías', 'slug' => 'peonias', 'description' => 'Peonías delicadas y románticas'],
            ['name' => 'Lirios', 'slug' => 'lirios', 'description' => 'Lirios elegantes y puros'],
            ['name' => 'Claveles', 'slug' => 'claveles', 'description' => 'Claveles coloridos y duraderos'],
            ['name' => 'Margaritas', 'slug' => 'margaritas', 'description' => 'Margaritas frescas y naturales'],
        ];

        foreach ($categories as $categoryData) {
            Category::firstOrCreate(
                ['slug' => $categoryData['slug']],
                $categoryData
            );
        }

        // Obtener IDs de categorías
        $rosasId = Category::where('slug', 'rosas')->first()->id;
        $tulipanesId = Category::where('slug', 'tulipanes')->first()->id;
        $girasolesId = Category::where('slug', 'girasoles')->first()->id;
        $orquideasId = Category::where('slug', 'orquideas')->first()->id;
        $peoniasId = Category::where('slug', 'peonias')->first()->id;
        $liriosId = Category::where('slug', 'lirios')->first()->id;
        $clavelesId = Category::where('slug', 'claveles')->first()->id;
        $margaritasId = Category::where('slug', 'margaritas')->first()->id;

        // Array completo de las 19 flores del catálogo
        $flowers = [
            [
                'name' => 'Rosas Rojas Premium',
                'slug' => 'rosas-rojas-premium',
                'description' => 'Hermosas rosas rojas premium, perfectas para expresar amor y pasión. Flores frescas de la mejor calidad que simbolizan el amor verdadero y la pasión profunda.',
                'short_description' => 'Rosas rojas premium para expresar amor y pasión',
                'price' => 89.99,
                'original_price' => 89.99,
                'discount_percentage' => 0,
                'category_id' => $rosasId,
                'color' => 'Rojo',
                'occasion' => 'San Valentín',
                'images' => json_encode(['/img/catalogo/imagencatalogo1.webp']),
                'rating' => 4.9,
                'reviews_count' => 124,
                'stock' => 25,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 150,
                'sort_order' => 1,
            ],
            [
                'name' => 'Tulipanes Holandeses',
                'slug' => 'tulipanes-holandeses',
                'description' => 'Tulipanes holandeses frescos y coloridos, ideales para alegrar cualquier día especial. Importados directamente de Holanda para garantizar la mejor calidad.',
                'short_description' => 'Tulipanes holandeses frescos y coloridos',
                'price' => 65.99,
                'original_price' => 65.99,
                'discount_percentage' => 0,
                'category_id' => $tulipanesId,
                'color' => 'Multicolor',
                'occasion' => 'Cumpleaños',
                'images' => json_encode(['/img/catalogo/imagencatalogo2.webp']),
                'rating' => 4.8,
                'reviews_count' => 98,
                'stock' => 18,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 120,
                'sort_order' => 2,
            ],
            [
                'name' => 'Girasoles Gigantes',
                'slug' => 'girasoles-gigantes',
                'description' => 'Girasoles gigantes que irradian alegría y positividad, perfectos para iluminar cualquier espacio. Simbolizan la lealtad y la adoración.',
                'short_description' => 'Girasoles gigantes que irradian alegría',
                'price' => 55.99,
                'original_price' => 65.99,
                'discount_percentage' => 15,
                'category_id' => $girasolesId,
                'color' => 'Amarillo',
                'occasion' => 'Solo porque sí',
                'images' => json_encode(['/img/catalogo/imagencatalogo3.webp']),
                'rating' => 4.7,
                'reviews_count' => 156,
                'stock' => 12,
                'is_featured' => false,
                'is_on_sale' => true,
                'is_active' => true,
                'views' => 95,
                'sort_order' => 3,
            ],
            [
                'name' => 'Orquídeas Exóticas',
                'slug' => 'orquideas-exoticas',
                'description' => 'Orquídeas exóticas de rara belleza, símbolo de elegancia y sofisticación. Perfectas para ocasiones especiales que requieren un toque de distinción.',
                'short_description' => 'Orquídeas exóticas de rara belleza',
                'price' => 125.99,
                'original_price' => 125.99,
                'discount_percentage' => 0,
                'category_id' => $orquideasId,
                'color' => 'Morado',
                'occasion' => 'Aniversario',
                'images' => json_encode(['/img/catalogo/imagencatalogo4.webp']),
                'rating' => 4.9,
                'reviews_count' => 87,
                'stock' => 8,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 200,
                'sort_order' => 4,
            ],
            [
                'name' => 'Peonías Rosadas',
                'slug' => 'peonias-rosadas',
                'description' => 'Peonías rosadas delicadas y románticas, perfectas para celebraciones especiales y bodas. Simbolizan la honor, la riqueza y el honor.',
                'short_description' => 'Peonías rosadas delicadas y románticas',
                'price' => 95.99,
                'original_price' => 95.99,
                'discount_percentage' => 0,
                'category_id' => $peoniasId,
                'color' => 'Rosa',
                'occasion' => 'Boda',
                'images' => json_encode(['/img/catalogo/imagencatalogo5.webp']),
                'rating' => 4.8,
                'reviews_count' => 143,
                'stock' => 15,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 110,
                'sort_order' => 5,
            ],
            [
                'name' => 'Lirios Blancos',
                'slug' => 'lirios-blancos',
                'description' => 'Lirios blancos puros y elegantes, símbolo de paz y pureza para momentos importantes. Ideales para expresar respeto y condolencias.',
                'short_description' => 'Lirios blancos puros y elegantes',
                'price' => 75.99,
                'original_price' => 75.99,
                'discount_percentage' => 0,
                'category_id' => $liriosId,
                'color' => 'Blanco',
                'occasion' => 'Condolencias',
                'images' => json_encode(['/img/catalogo/imagencatalogo6.webp']),
                'rating' => 4.6,
                'reviews_count' => 201,
                'stock' => 20,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 180,
                'sort_order' => 6,
            ],
            [
                'name' => 'Rosas Blancas Elegantes',
                'slug' => 'rosas-blancas-elegantes',
                'description' => 'Rosas blancas elegantes que representan pureza y nuevos comienzos. Perfectas para bodas y ceremonias importantes.',
                'short_description' => 'Rosas blancas que representan pureza',
                'price' => 79.99,
                'original_price' => 79.99,
                'discount_percentage' => 0,
                'category_id' => $rosasId,
                'color' => 'Blanco',
                'occasion' => 'Boda',
                'images' => json_encode(['/img/catalogo/imagencatalogo7.webp']),
                'rating' => 4.8,
                'reviews_count' => 112,
                'stock' => 22,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 140,
                'sort_order' => 7,
            ],
            [
                'name' => 'Claveles Coloridos',
                'slug' => 'claveles-coloridos',
                'description' => 'Claveles coloridos y alegres, perfectos para demostrar cariño y aprecio. Duraderos y con una fragancia deliciosa.',
                'short_description' => 'Claveles coloridos y alegres',
                'price' => 39.99,
                'original_price' => 45.99,
                'discount_percentage' => 13,
                'category_id' => $clavelesId,
                'color' => 'Multicolor',
                'occasion' => 'Día de la Madre',
                'images' => json_encode(['/img/catalogo/imagencatalogo8.webp']),
                'rating' => 4.5,
                'reviews_count' => 76,
                'stock' => 30,
                'is_featured' => false,
                'is_on_sale' => true,
                'is_active' => true,
                'views' => 85,
                'sort_order' => 8,
            ],
            [
                'name' => 'Margaritas Frescas',
                'slug' => 'margaritas-frescas',
                'description' => 'Margaritas frescas que simbolizan inocencia y pureza, ideales para cualquier momento. Perfectas para regalos espontáneos.',
                'short_description' => 'Margaritas frescas que simbolizan inocencia',
                'price' => 35.99,
                'original_price' => 35.99,
                'discount_percentage' => 0,
                'category_id' => $margaritasId,
                'color' => 'Blanco',
                'occasion' => 'Solo porque sí',
                'images' => json_encode(['/img/catalogo/imagencatalogo9.webp']),
                'rating' => 4.6,
                'reviews_count' => 89,
                'stock' => 25,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 70,
                'sort_order' => 9,
            ],
            [
                'name' => 'Rosas Rojas Intensas',
                'slug' => 'rosas-rojas-intensas',
                'description' => 'Rosas rojas de color intenso, perfectas para expresar pasión y amor verdadero. Seleccionadas por su color vibrante y aroma cautivador.',
                'short_description' => 'Rosas rojas de color intenso',
                'price' => 99.99,
                'original_price' => 99.99,
                'discount_percentage' => 0,
                'category_id' => $rosasId,
                'color' => 'Rojo',
                'occasion' => 'San Valentín',
                'images' => json_encode(['/img/catalogo/imagencatalogo10.webp']),
                'rating' => 4.9,
                'reviews_count' => 234,
                'stock' => 15,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 250,
                'sort_order' => 10,
            ],
            [
                'name' => 'Tulipanes Primaverales',
                'slug' => 'tulipanes-primaverales',
                'description' => 'Tulipanes primaverales en tonos rosados, ideales para celebrar la renovación y la alegría. Frescos y llenos de vitalidad.',
                'short_description' => 'Tulipanes primaverales en tonos rosados',
                'price' => 72.99,
                'original_price' => 72.99,
                'discount_percentage' => 0,
                'category_id' => $tulipanesId,
                'color' => 'Rosa',
                'occasion' => 'Cumpleaños',
                'images' => json_encode(['/img/catalogo/imagencatalogo11.webp']),
                'rating' => 4.7,
                'reviews_count' => 145,
                'stock' => 20,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 100,
                'sort_order' => 11,
            ],
            [
                'name' => 'Girasoles Dorados',
                'slug' => 'girasoles-dorados',
                'description' => 'Girasoles dorados radiantes que simbolizan éxito y nuevos comienzos. Perfectos para graduaciones y celebraciones de logros.',
                'short_description' => 'Girasoles dorados radiantes',
                'price' => 62.99,
                'original_price' => 62.99,
                'discount_percentage' => 0,
                'category_id' => $girasolesId,
                'color' => 'Amarillo',
                'occasion' => 'Graduación',
                'images' => json_encode(['/img/catalogo/imagencatalogo12.webp']),
                'rating' => 4.8,
                'reviews_count' => 167,
                'stock' => 18,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 130,
                'sort_order' => 12,
            ],
            [
                'name' => 'Orquídeas Blancas',
                'slug' => 'orquideas-blancas',
                'description' => 'Orquídeas blancas de pureza excepcional, perfectas para ocasiones elegantes. Simbolizan la pureza y la fortaleza.',
                'short_description' => 'Orquídeas blancas de pureza excepcional',
                'price' => 135.99,
                'original_price' => 135.99,
                'discount_percentage' => 0,
                'category_id' => $orquideasId,
                'color' => 'Blanco',
                'occasion' => 'Boda',
                'images' => json_encode(['/img/catalogo/imagencatalogo13.webp']),
                'rating' => 4.9,
                'reviews_count' => 92,
                'stock' => 6,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 190,
                'sort_order' => 13,
            ],
            [
                'name' => 'Peonías Coral',
                'slug' => 'peonias-coral',
                'description' => 'Peonías en tonos coral vibrantes, ideales para celebrar momentos especiales. Su color único las hace perfectas para ocasiones memorables.',
                'short_description' => 'Peonías en tonos coral vibrantes',
                'price' => 89.99,
                'original_price' => 105.99,
                'discount_percentage' => 15,
                'category_id' => $peoniasId,
                'color' => 'Naranja',
                'occasion' => 'Aniversario',
                'images' => json_encode(['/img/catalogo/imagencatalogo14.webp']),
                'rating' => 4.7,
                'reviews_count' => 118,
                'stock' => 10,
                'is_featured' => false,
                'is_on_sale' => true,
                'is_active' => true,
                'views' => 90,
                'sort_order' => 14,
            ],
            [
                'name' => 'Lirios Amarillos',
                'slug' => 'lirios-amarillos',
                'description' => 'Lirios amarillos brillantes que traen luz y optimismo a cualquier espacio. Simbolizan la gratitud y la alegría.',
                'short_description' => 'Lirios amarillos brillantes',
                'price' => 68.99,
                'original_price' => 68.99,
                'discount_percentage' => 0,
                'category_id' => $liriosId,
                'color' => 'Amarillo',
                'occasion' => 'Solo porque sí',
                'images' => json_encode(['/img/catalogo/imagencatalogo15.webp']),
                'rating' => 4.6,
                'reviews_count' => 134,
                'stock' => 16,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 80,
                'sort_order' => 15,
            ],
            [
                'name' => 'Rosas Mixtas Premium',
                'slug' => 'rosas-mixtas-premium',
                'description' => 'Arreglo premium de rosas en colores variados, perfecto para expresar múltiples emociones. Una selección cuidadosa de nuestras mejores rosas.',
                'short_description' => 'Arreglo premium de rosas en colores variados',
                'price' => 115.99,
                'original_price' => 115.99,
                'discount_percentage' => 0,
                'category_id' => $rosasId,
                'color' => 'Multicolor',
                'occasion' => 'Día de la Madre',
                'images' => json_encode(['/img/catalogo/imagencatalogo16.webp']),
                'rating' => 4.8,
                'reviews_count' => 203,
                'stock' => 12,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 170,
                'sort_order' => 16,
            ],
            [
                'name' => 'Claveles Rosados',
                'slug' => 'claveles-rosados',
                'description' => 'Claveles rosados delicados que expresan gratitud y admiración. Perfectos para mostrar aprecio hacia alguien especial.',
                'short_description' => 'Claveles rosados delicados',
                'price' => 42.99,
                'original_price' => 42.99,
                'discount_percentage' => 0,
                'category_id' => $clavelesId,
                'color' => 'Rosa',
                'occasion' => 'Cumpleaños',
                'images' => json_encode(['/img/catalogo/imagencatalogo17.webp']),
                'rating' => 4.5,
                'reviews_count' => 89,
                'stock' => 28,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 65,
                'sort_order' => 17,
            ],
            [
                'name' => 'Margaritas Silvestres',
                'slug' => 'margaritas-silvestres',
                'description' => 'Margaritas silvestres naturales que aportan frescura y simplicidad. Perfectas para crear un ambiente rústico y natural.',
                'short_description' => 'Margaritas silvestres naturales',
                'price' => 38.99,
                'original_price' => 38.99,
                'discount_percentage' => 0,
                'category_id' => $margaritasId,
                'color' => 'Blanco',
                'occasion' => 'Solo porque sí',
                'images' => json_encode(['/img/catalogo/imagencatalogo18.webp']),
                'rating' => 4.4,
                'reviews_count' => 76,
                'stock' => 35,
                'is_featured' => false,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 55,
                'sort_order' => 18,
            ],
            [
                'name' => 'Bouquet Especial',
                'slug' => 'bouquet-especial',
                'description' => 'Bouquet especial de diseñador con flores selectas, perfecto para ocasiones únicas. Una creación artística que combina las mejores flores de temporada.',
                'short_description' => 'Bouquet especial de diseñador',
                'price' => 149.99,
                'original_price' => 149.99,
                'discount_percentage' => 0,
                'category_id' => $rosasId,
                'color' => 'Multicolor',
                'occasion' => 'Boda',
                'images' => json_encode(['/img/catalogo/imagencatalogo19.webp']),
                'rating' => 5.0,
                'reviews_count' => 156,
                'stock' => 5,
                'is_featured' => true,
                'is_on_sale' => false,
                'is_active' => true,
                'views' => 300,
                'sort_order' => 19,
            ],
        ];

        // Insertar o actualizar las flores
        foreach ($flowers as $flowerData) {
            Flower::updateOrCreate(
                ['slug' => $flowerData['slug']],
                $flowerData
            );
        }

        $this->command->info('Se han creado/actualizado ' . count($flowers) . ' flores en el catálogo.');
    }
}
